name: Release

on:
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm i -g pnpm
      - run: pnpm install
      - run: rm .gitignore
      - run: pnpm build
      - run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
